#!/bin/sh
set -eu

cups_user="${CUPS_USER:-print}"
cups_password="${CUPS_PASSWORD:-print}"
printer_name="${PRINTER_NAME:-HP_Smart_Tank_515}"
ldap_enabled="${LDAP_ENABLED:-false}"

# ── 1. Local service account (always created — used by the Flask web app) ──
if ! id "$cups_user" >/dev/null 2>&1; then
    echo "CUPS_USER '$cups_user' does not exist in the image" >&2
    exit 1
fi
printf '%s:%s\n' "$cups_user" "$cups_password" | chpasswd

# ── 2. AD / LDAP PAM integration (optional) ───────────────────────────────
if [ "$ldap_enabled" = "true" ]; then
    ldap_host="${LDAP_HOST:-}"
    ldap_port="${LDAP_PORT:-389}"
    ldap_use_ssl="${LDAP_USE_SSL:-false}"
    ldap_base_dn="${LDAP_BASE_DN:-}"
    ldap_bind_dn="${LDAP_BIND_DN:-}"
    ldap_bind_password="${LDAP_BIND_PASSWORD:-}"

    if [ -z "$ldap_host" ] || [ -z "$ldap_base_dn" ]; then
        echo "[cups-entrypoint] LDAP_ENABLED=true but LDAP_HOST or LDAP_BASE_DN is empty — skipping LDAP PAM setup" >&2
    else
        echo "[cups-entrypoint] Configuring nslcd for AD/LDAP authentication..."

        # Determine URI scheme
        if [ "$ldap_use_ssl" = "true" ]; then
            ldap_uri="ldaps://${ldap_host}:${ldap_port}"
        else
            ldap_uri="ldap://${ldap_host}:${ldap_port}"
        fi

        # Generate nslcd.conf
        cat > /etc/nslcd.conf <<NSLCD_EOF
# Auto-generated by cups-entrypoint — do not edit manually
uid nslcd
gid nslcd

uri ${ldap_uri}
base ${ldap_base_dn}
NSLCD_EOF

        # Add bind credentials if provided
        if [ -n "$ldap_bind_dn" ] && [ -n "$ldap_bind_password" ]; then
            cat >> /etc/nslcd.conf <<NSLCD_BIND_EOF
binddn ${ldap_bind_dn}
bindpw ${ldap_bind_password}
NSLCD_BIND_EOF
        fi

        # AD-specific attribute mappings
        cat >> /etc/nslcd.conf <<NSLCD_MAP_EOF

# Active Directory attribute mappings
pagesize 1000
referrals off
filter passwd (&(objectClass=user)(!(objectClass=computer))(sAMAccountName=*))
map passwd uid sAMAccountName
map passwd uidNumber objectSid:S-1-5-21-0-0-0
map passwd gidNumber primaryGroupID
map passwd homeDirectory "/home/\$sAMAccountName"
map passwd loginShell "/bin/false"
map passwd gecos displayName

filter group (objectClass=group)
map group cn sAMAccountName
map group gidNumber objectSid:S-1-5-21-0-0-0
NSLCD_MAP_EOF

        # TLS settings for non-SSL LDAP (StartTLS or no encryption)
        if [ "$ldap_use_ssl" != "true" ]; then
            cat >> /etc/nslcd.conf <<NSLCD_TLS_EOF

# Accept any certificate (typical for internal AD; tighten for production)
ssl off
tls_reqcert never
NSLCD_TLS_EOF
        else
            cat >> /etc/nslcd.conf <<NSLCD_TLS_EOF

ssl on
tls_reqcert never
NSLCD_TLS_EOF
        fi

        chmod 600 /etc/nslcd.conf

        # Configure NSS to use LDAP (add ldap if not already present)
        sed -i -E '/^(passwd|group|shadow):/ { /(^|[[:space:]])ldap([[:space:]]|$)/! s/$/ ldap/; }' /etc/nsswitch.conf

        # Start nslcd in the background
        nslcd
        echo "[cups-entrypoint] nslcd started — AD users can now authenticate via PAM"

        # Set printer policy to 'authenticated' (requires AD creds for IPP printing)
        # This runs after cupsd starts, so we schedule it
        (
            # Wait for cupsd to be ready
            for _i in $(seq 1 30); do
                if lpstat -r >/dev/null 2>&1; then
                    break
                fi
                sleep 1
            done
            if lpstat -p "$printer_name" >/dev/null 2>&1; then
                lpadmin -p "$printer_name" -o printer-op-policy=authenticated
                echo "[cups-entrypoint] Set printer '$printer_name' policy to 'authenticated'"
            else
                echo "[cups-entrypoint] Printer '$printer_name' not found — skipping policy" >&2
            fi
        ) &
    fi
else
    # AD disabled — set default policy (no auth for IPP printing)
    (
        for _i in $(seq 1 30); do
            if lpstat -r >/dev/null 2>&1; then
                break
            fi
            sleep 1
        done
        if lpstat -p "$printer_name" >/dev/null 2>&1; then
            lpadmin -p "$printer_name" -o printer-op-policy=default
            echo "[cups-entrypoint] Set printer '$printer_name' policy to 'default' (AD disabled)"
        fi
    ) &
fi

exec "$@"
