#!/bin/bash
# setup-cups-ldap.sh — Configure PAM/NSS LDAP (nslcd) for CUPS AD authentication
#
# For bare-metal / LXC hosts. Can be run standalone or called by install.sh.
# Reads LDAP settings from .env (if found) or from environment variables.
#
# Usage:
#   sudo bash setup-cups-ldap.sh                  # reads from .env in current dir
#   sudo bash setup-cups-ldap.sh /path/to/.env    # reads from specified .env
#   sudo LDAP_HOST=ad.example.com ... bash setup-cups-ldap.sh  # from env vars

set -e

# ── Load settings ──────────────────────────────────────────────────────────
ENV_FILE="${1:-$(dirname "$0")/../.env}"
if [ -f "$ENV_FILE" ]; then
    echo "📄 Loading settings from $ENV_FILE"
    set -a
    # shellcheck disable=SC1090
    . "$ENV_FILE"
    set +a
fi

LDAP_HOST="${LDAP_HOST:-}"
LDAP_PORT="${LDAP_PORT:-389}"
LDAP_USE_SSL="${LDAP_USE_SSL:-false}"
LDAP_BASE_DN="${LDAP_BASE_DN:-}"
LDAP_BIND_DN="${LDAP_BIND_DN:-}"
LDAP_BIND_PASSWORD="${LDAP_BIND_PASSWORD:-}"
PRINTER_NAME="${PRINTER_NAME:-}"

# ── Validate ───────────────────────────────────────────────────────────────
if [ -z "$LDAP_HOST" ]; then
    echo "❌ LDAP_HOST is not set. Set it in .env or as an environment variable."
    exit 1
fi
if [ -z "$LDAP_BASE_DN" ]; then
    echo "❌ LDAP_BASE_DN is not set. Set it in .env or as an environment variable."
    exit 1
fi

echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║     CUPS AD/LDAP Authentication Setup (nslcd)            ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "  LDAP Host:    $LDAP_HOST:$LDAP_PORT"
echo "  Base DN:      $LDAP_BASE_DN"
echo "  SSL:          $LDAP_USE_SSL"
echo "  Bind DN:      ${LDAP_BIND_DN:-(anonymous)}"
echo "  Printer:      ${PRINTER_NAME:-(will be configured separately)}"
echo ""

# ── 1. Install packages ───────────────────────────────────────────────────
echo "📦 Step 1: Installing nslcd + PAM/NSS LDAP packages..."
DEBIAN_FRONTEND=noninteractive apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    nslcd libnss-ldapd libpam-ldapd

echo "✅ Packages installed"
echo ""

# ── 2. Generate nslcd.conf ────────────────────────────────────────────────
echo "⚙️  Step 2: Generating /etc/nslcd.conf..."

# Determine URI scheme
if [ "$LDAP_USE_SSL" = "true" ]; then
    LDAP_URI="ldaps://${LDAP_HOST}:${LDAP_PORT}"
else
    LDAP_URI="ldap://${LDAP_HOST}:${LDAP_PORT}"
fi

cat > /etc/nslcd.conf <<EOF
# Auto-generated by setup-cups-ldap.sh — edit with care
uid nslcd
gid nslcd

uri ${LDAP_URI}
base ${LDAP_BASE_DN}
EOF

# Add bind credentials if provided
if [ -n "$LDAP_BIND_DN" ] && [ -n "$LDAP_BIND_PASSWORD" ]; then
    cat >> /etc/nslcd.conf <<EOF
binddn ${LDAP_BIND_DN}
bindpw ${LDAP_BIND_PASSWORD}
EOF
fi

# AD-specific attribute mappings
cat >> /etc/nslcd.conf <<'EOF'

# Active Directory attribute mappings
pagesize 1000
referrals off
filter passwd (&(objectClass=user)(!(objectClass=computer))(sAMAccountName=*))
map passwd uid sAMAccountName
map passwd uidNumber objectSid:S-1-5-21-0-0-0
map passwd gidNumber primaryGroupID
map passwd homeDirectory "/home/$sAMAccountName"
map passwd loginShell "/bin/false"
map passwd gecos displayName

filter group (objectClass=group)
map group cn sAMAccountName
map group gidNumber objectSid:S-1-5-21-0-0-0
EOF

# TLS settings
if [ "$LDAP_USE_SSL" = "true" ]; then
    cat >> /etc/nslcd.conf <<EOF

ssl on
tls_reqcert never
EOF
else
    cat >> /etc/nslcd.conf <<EOF

ssl off
tls_reqcert never
EOF
fi

chmod 600 /etc/nslcd.conf
echo "✅ /etc/nslcd.conf generated"
echo ""

# ── 3. Update NSS ─────────────────────────────────────────────────────────
echo "⚙️  Step 3: Updating /etc/nsswitch.conf..."
sed -i -E '/^(passwd|group|shadow):/ { /(^|[[:space:]])ldap([[:space:]]|$)/! s/$/ ldap/; }' /etc/nsswitch.conf
echo "✅ NSS configured for LDAP"
echo ""

# ── 4. Restart nslcd ──────────────────────────────────────────────────────
echo "🔄 Step 4: Restarting nslcd..."
systemctl enable nslcd
systemctl restart nslcd
echo "✅ nslcd running"
echo ""

# ── 5. Configure CUPS printer policy ──────────────────────────────────────
if [ -n "$PRINTER_NAME" ]; then
    echo "🖨️  Step 5: Setting printer '$PRINTER_NAME' policy to 'authenticated'..."
    if lpstat -p "$PRINTER_NAME" >/dev/null 2>&1; then
        lpadmin -p "$PRINTER_NAME" -o printer-op-policy=authenticated
        systemctl restart cups
        echo "✅ Printer policy set to 'authenticated'"
    else
        echo "⚠️  Printer '$PRINTER_NAME' not found in CUPS. Set the policy manually later:"
        echo "   lpadmin -p YOUR_PRINTER -o printer-op-policy=authenticated"
    fi
else
    echo "ℹ️  Step 5: No PRINTER_NAME set — configure the policy manually:"
    echo "   lpadmin -p YOUR_PRINTER -o printer-op-policy=authenticated"
fi
echo ""

# ── 6. Test ────────────────────────────────────────────────────────────────
echo "🔍 Step 6: Testing AD user resolution..."
echo "   Run: getent passwd <ad-username>"
echo "   If it returns user info, AD/LDAP PAM is working."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ CUPS AD/LDAP authentication setup complete!"
echo ""
echo "📱 Android/iOS users will now be prompted for AD credentials"
echo "   when printing to this printer for the first time."
echo ""
echo "🔐 The web app (Flask) still uses the local CUPS_USER service"
echo "   account — it is not affected by this change."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
